language: scala
sudo: false

scala:
  - 2.12.6

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - sbt coverageReport
  - sbt coverageAggregate
